config/routes.rb
Rails.application.routes.draw do
  resources :tickets

  resources :passengers

  resources :flights

end

app/models/flight.rb
class Flight < ActiveRecord::Base
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
  belongs_to :flight
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
  belongs_to :flight
  belongs_to :passenger
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  before_action :set_flight, only: [:show, :edit, :update, :destroy]

  # GET /flights
  # GET /flights.json
  def index
    @flights = Flight.all
  end

  # GET /flights/1
  # GET /flights/1.json
  def show
  end

  # GET /flights/new
  def new
    @flight = Flight.new
  end

  # GET /flights/1/edit
  def edit
  end

  # POST /flights
  # POST /flights.json
  def create
    @flight = Flight.new(flight_params)

    respond_to do |format|
      if @flight.save
        format.html { redirect_to @flight, notice: 'Flight was successfully created.' }
        format.json { render :show, status: :created, location: @flight }
      else
        format.html { render :new }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flights/1
  # PATCH/PUT /flights/1.json
  def update
    respond_to do |format|
      if @flight.update(flight_params)
        format.html { redirect_to @flight, notice: 'Flight was successfully updated.' }
        format.json { render :show, status: :ok, location: @flight }
      else
        format.html { render :edit }
        format.json { render json: @flight.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flights/1
  # DELETE /flights/1.json
  def destroy
    @flight.destroy
    respond_to do |format|
      format.html { redirect_to flights_url, notice: 'Flight was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flight
      @flight = Flight.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def flight_params
      params.require(:flight).permit(:flight_number, :airline, :from, :destination, :departure)
    end
end

app/controllers/passengers_controller.rb
class PassengersController < ApplicationController
  before_action :set_passenger, only: [:show, :edit, :update, :destroy]

  # GET /passengers
  # GET /passengers.json
  def index
    @passengers = Passenger.all
  end

  # GET /passengers/1
  # GET /passengers/1.json
  def show
  end

  # GET /passengers/new
  def new
    @passenger = Passenger.new
    @flights = Flight.new
  end

  # GET /passengers/1/edit
  def edit
  end

  # POST /passengers
  # POST /passengers.json
  def create
    @passenger = Passenger.new(passenger_params)
    respond_to do |format|
      if @passenger.save
        format.html { redirect_to @passenger, notice: 'Passenger was successfully created.' }
        format.json { render :show, status: :created, location: @passenger }
      else
        format.html { render :new }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passengers/1
  # PATCH/PUT /passengers/1.json
  def update
    respond_to do |format|
      if @passenger.update(passenger_params)
        format.html { redirect_to @passenger, notice: 'Passenger was successfully updated.' }
        format.json { render :show, status: :ok, location: @passenger }
      else
        format.html { render :edit }
        format.json { render json: @passenger.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passengers/1
  # DELETE /passengers/1.json
  def destroy
    @passenger.destroy
    respond_to do |format|
      format.html { redirect_to passengers_url, notice: 'Passenger was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_passenger
      @passenger = Passenger.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def passenger_params
      params.require(:passenger).permit(:passport_id, :name, :age, :flight_id)
    end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :set_ticket, only: [:show, :edit, :update, :destroy]

  # GET /tickets
  # GET /tickets.json
  def index
    @tickets = Ticket.all
  end

  # GET /tickets/1
  # GET /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets
  # POST /tickets.json
  def create
    @ticket = Ticket.new(ticket_params)

    respond_to do |format|
      if @ticket.save
        format.html { redirect_to @ticket, notice: 'Ticket was successfully created.' }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1
  # PATCH/PUT /tickets/1.json
  def update
    respond_to do |format|
      if @ticket.update(ticket_params)
        format.html { redirect_to @ticket, notice: 'Ticket was successfully updated.' }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1
  # DELETE /tickets/1.json
  def destroy
    @ticket.destroy
    respond_to do |format|
      format.html { redirect_to tickets_url, notice: 'Ticket was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_ticket
      @ticket = Ticket.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def ticket_params
      params.require(:ticket).permit(:ticket_id, :flight_id, :passenger_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/helpers/passengers_helper.rb
module PassengersHelper
end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/flights/_form.html.erb
<%= form_for(@flight) do |f| %>
  <% if @flight.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@flight.errors.count, "error") %> prohibited this flight from being saved:</h2>

      <ul>
      <% @flight.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :flight_number %><br>
    <%= f.number_field :flight_number %>
  </div>
  <div class="field">
    <%= f.label :airline %><br>
    <%= f.text_field :airline %>
  </div>
    <div class="field">
    <%= f.label :from %><br>
    <%= f.text_field :from %>
  </div>
  <div class="field">
    <%= f.label :destination %><br>
    <%= f.text_field :destination %>
  </div>
  <div class="field">
    <%= f.label :departure %><br>
    <%= f.datetime_select :departure %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/flights/edit.html.erb
<h1>Editing Flight</h1>

<%= render 'form' %>

<%= link_to 'Show', @flight %> |
<%= link_to 'Back', flights_path %>

app/views/flights/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Flights</h1>

<table>
  <thead>
    <tr>
      <th>Flight number</th>
      <th>Airline</th>
      <th>From</th>
      <th>Destination</th>
      <th>Departure</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flights.each do |flight| %>
      <tr>
        <td><%= flight.flight_number %></td>
        <td><%= flight.airline %></td>
        <td><%= flight.from %></td>
        <td><%= flight.destination %></td>
        <td><%= flight.departure %></td>
        <td><%= link_to 'Show', flight %></td>
        <td><%= link_to 'Edit', edit_flight_path(flight) %></td>
        <td><%= link_to 'Destroy', flight, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flight', new_flight_path %>

app/views/flights/new.html.erb
<h1>New Flight</h1>

<%= render 'form' %>

<%= link_to 'Back', flights_path %>

app/views/flights/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Flight number:</strong>
  <%= @flight.flight_number %>
</p>

<p>
  <strong>Airline:</strong>
  <%= @flight.airline %>
</p>

<p>
  <strong>From:</strong>
  <%= @flight.from %>
</p>

<p>
  <strong>Destination:</strong>
  <%= @flight.destination %>
</p>

<p>
  <strong>Departure:</strong>
  <%= @flight.departure %>
</p>

<%= link_to 'Edit', edit_flight_path(@flight) %> |
<%= link_to 'Back', flights_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AirportGroup</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/passengers/_form.html.erb
<%= form_for(@passenger) do |f| %>
  <% if @passenger.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@passenger.errors.count, "error") %> prohibited this passenger from being saved:</h2>

      <ul>
      <% @passenger.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :passport_id %><br>
    <%= f.text_field :passport_id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :age %><br>
    <%= f.number_field :age %>
  </div>
  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.text_field :flight_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/passengers/edit.html.erb
<h1>Editing Passenger</h1>

<%= render 'form' %>

<%= link_to 'Show', @passenger %> |
<%= link_to 'Back', passengers_path %>

app/views/passengers/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Passengers</h1>

<table>
  <thead>
    <tr>
      <th>Passport</th>
      <th>Name</th>
      <th>Age</th>
      <th>Flight</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passengers.each do |passenger| %>
      <tr>
        <td><%= passenger.passport_id %></td>
        <td><%= passenger.name %></td>
        <td><%= passenger.age %></td>
        <td><%= passenger.flight %></td>
        <td><%= link_to 'Show', passenger %></td>
        <td><%= link_to 'Edit', edit_passenger_path(passenger) %></td>
        <td><%= link_to 'Destroy', passenger, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Passenger', new_passenger_path %>

app/views/passengers/new.html.erb
<h1>New Passenger</h1>

<%= render 'form' %>

<%= link_to 'Back', passengers_path %>

app/views/passengers/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Passport:</strong>
  <%= @passenger.passport_id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @passenger.name %>
</p>

<p>
  <strong>Age:</strong>
  <%= @passenger.age %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @passenger.flight.flight_number %>
</p>

<%= link_to 'Edit', edit_passenger_path(@passenger) %> |
<%= link_to 'Back', passengers_path %>

app/views/tickets/_form.html.erb
<%= form_for(@ticket) do |f| %>
  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
      <% @ticket.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :ticket_id %><br>
    <%= f.text_field :ticket_id %>
  </div>
  <div class="field">
    <%= f.label :flight_id %><br>
    <%= f.text_field :flight_id %>
  </div>
  <div class="field">
    <%= f.label :passenger_id %><br>
    <%= f.text_field :passenger_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<h1>Editing Ticket</h1>

<%= render 'form' %>

<%= link_to 'Show', @ticket %> |
<%= link_to 'Back', tickets_path %>

app/views/tickets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tickets</h1>

<table>
  <thead>
    <tr>
      <th>Ticket</th>
      <th>Flight</th>
      <th>Passenger</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tickets.each do |ticket| %>
      <tr>
        <td><%= ticket.ticket_id %></td>
        <td><%= ticket.flight %></td>
        <td><%= ticket.passenger %></td>
        <td><%= link_to 'Show', ticket %></td>
        <td><%= link_to 'Edit', edit_ticket_path(ticket) %></td>
        <td><%= link_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Ticket', new_ticket_path %>

app/views/tickets/new.html.erb
<h1>New Ticket</h1>

<%= render 'form' %>

<%= link_to 'Back', tickets_path %>

app/views/tickets/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Ticket:</strong>
  <%= @ticket.ticket_id %>
</p>

<p>
  <strong>Flight:</strong>
  <%= @ticket.flight %>
</p>

<p>
  <strong>Passenger:</strong>
  <%= @ticket.passenger %>
</p>

<%= link_to 'Edit', edit_ticket_path(@ticket) %> |
<%= link_to 'Back', tickets_path %>